# Pytest configuration file.
# In the 'addopts' field you can manage the command-line options
# defaults.

[pytest]
addopts =
    -s -x -vv
    --capture=no
    --cov=tests/
    --json-report
    --json-report-file=.report.json
testpaths=tests/test_system
log_cli = true
log_cli_level = INFO
log_file = logs/test.log
log_cli_format = %(asctime)s,%(msecs)03d %(levelname)s %(filename)s %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers =
    API_REMOTE_COMMAND: Issue pwd in Linux console
    GENERIC_LINUX: Only Linux SUT